# For DigitalOcean App Platform
name: meetpoint-app
services:
  - name: meetpoint-server
    image:
      registry_type: DOCKER_HUB
      repository: maisoup/meetpoint-server
      tag: latest
  - name: meetpoint-nginx
    image:
      registry_type: DOCKER_HUB
      repository: maisoup/meetpoint-nginx
      tag: latest
    http_port: 80
    envs:
      - key: SERVER_API_URL
        value: http://meetpoint-server:5000
ingress:
  rules:
    - match:
        path:
          prefix: "/"
      component:
        name: meetpoint-nginx
        preserve_path_prefix: false
    - match:
        path:
          prefix: "/api"
      component:
        name: meetpoint-server
        preserve_path_prefix: false
