version: "3.8"

services:
  meetpoint-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env
    networks:
      - meetpoint-network
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  meetpoint-nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - "80:80"
    depends_on:
      - meetpoint-server
    networks:
      - meetpoint-network

networks:
  meetpoint-network:
