name: Deploy to Amazon Elastic Beanstalk

on:
  push:
    branches:
      - master

env:
  AWS_REGION: eu-north-1
  ECR_REPOSITORY_SERVER: meetpoint-server
  ECR_REPOSITORY_CLIENT: meetpoint-client
  EB_APP_NAME: MeetPoint
  EB_ENV_NAME: Meetpoint-env

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@13d241b293754004c80624b5567555c4a39ffbe3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@aaf69d68aa3fb14c1d5a6be9ac61fe15b48453a2

      - name: Build, tag, and push server image to Amazon ECR
        run: |
          cd server
          docker build -t ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY_SERVER }}:${{ github.sha }} .
          docker push ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY_SERVER }}:${{ github.sha }}

      - name: Build, tag, and push client image to Amazon ECR
        run: |
          cd client
          docker build -t ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY_CLIENT }}:${{ github.sha }} .
          docker push ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY_CLIENT }}:${{ github.sha }}

      - name: Update Dockerrun file with new image URIs
        run: |
          sed -i 's|485229747515.dkr.ecr.eu-north-1.amazonaws.com/meetpoint-server|${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY_SERVER }}:${{ github.sha }}|g' Dockerrun.aws.json
          sed -i 's|485229747515.dkr.ecr.eu-north-1.amazonaws.com/meetpoint-client|${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY_CLIENT }}:${{ github.sha }}|g' Dockerrun.aws.json

      - name: Deploy to Elastic Beanstalk
        uses: aws-actions/aws-elastic-beanstalk-deploy@v1
        with:
          application-name: ${{ env.EB_APP_NAME }}
          environment-name: ${{ env.EB_ENV_NAME }}
          region: ${{ env.AWS_REGION }}
          version-label: ${{ github.sha }}
          source-bundle: Dockerrun.aws.json
