name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      env:
        AWS_REGION: eu-north-1

    - name: Build and push meetpoint-server
      uses: docker/build-push-action@v2
      with:
        context: ./server
        push: true
        tags: ${{ steps.login-ecr.outputs.registry }}/meetpoint-server:latest

    - name: Build and push meetpoint-client
      uses: docker/build-push-action@v2
      with:
        context: ./client
        push: true
        tags: ${{ steps.login-ecr.outputs.registry }}/meetpoint-client:latest

    - name: Deploy to Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v16
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
        aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
        application_name: MeetPoint
        environment_name: MeetPoint-env
        region: eu-north-1
